export const FETCH_RULES_START = 'FETCH_RULES_START';
export const FETCH_RULES_SUCCESS = 'FETCH_RULES_SUCCESS';
export const FETCH_RULES_FAILURE = 'FETCH_RULES_FAILURE';

export const SELECT_ITEM = 'SELECT_ITEM';

export const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const PROCESS_MOVIES_DATA = 'PROCESS_MOVIES_DATA';