import { RULE_COLORS } from './ruleColors';
import { BOOTSTRAP_COLORS } from './bootstrapColors';

const COLORS_MAP = {
    [RULE_COLORS.RED]: BOOTSTRAP_COLORS.DANGER,
    [RULE_COLORS.BLUE]: BOOTSTRAP_COLORS.PRIMARY,
    [RULE_COLORS.GREEN]: BOOTSTRAP_COLORS.SUCCESS,
    [RULE_COLORS.ORANGE]: BOOTSTRAP_COLORS.SECONDARY,
    [RULE_COLORS.YELLOW]: BOOTSTRAP_COLORS.WARNING,
    [RULE_COLORS.NEUTRAL]: BOOTSTRAP_COLORS.SECONDARY

};

export default COLORS_MAP;